### PR TITLE
Rest api v1

### PR DESCRIPTION
**Pull request by ShilpaGhanashyamGore**
Rest APIs for group2

### CODE REVIEW

**Comment by lgfrbcsgo** [comment]
Nice, that's a good start. We have to port it to swagger though which shouldn't be to big of a deal.

**Comment by felixschorer** [comment]
Nice, that's a good start! 👍 
We have to port it to swagger though which shouldn't be to big of a deal. 

I can help you setting up the paths and methods. It would be cool if someone could approve my pull request so I can start building your API skeleton.
I'll then create something similar to my open pull request and leave the implementation of the handlers to you. Basically you just have to copy and past in your current implementation as swagger also uses Express.

**Comment by ShilpaGhanashyamGore** [comment]
@lgfrbcsgo :Thank you for the feedback! I will make one .Will post questions , if any.

**Comment by felixschorer** [comment]
@ShilpaGhanashyamGore Even better, less work for me 😃 
I'd suggest you merge my pull request and work off of that. It should give you a lot of examples.

**Comment by felixschorer** [comment]
@ShilpaGhanashyamGore The problem I see right now is time. It would probably be faster for me to build a skeleton for you. You could implement `sequelize` in the mean time as you've got a better understanding of your database structure

**Comment by TimHenkelmann** [comment]
@lgfrbcsgo Yes, I just finished the script to create our db schema with Sequelize. You can find it here #11

**Comment by kordianbruck** [comment]
I mean this is good work, but does not use swagger. So can we close this PR?

**Comment by ShilpaGhanashyamGore** [comment]
@kordianbruck  : Thank you .
But it is disappointing to see one's effort not making it to the main branch :-( :-(
I wish I was informed of Swagger a little earlier .I spent a lot of effort making the first one and then adapting it to the new schema .You may close the PR.
 I am new to swagger and at the moment I would like to know what is the next move .
@lgfrbcsgo , @kordianbruck  : I was AFK , Please guide me on what should I do next ?

**Comment by kordianbruck** [comment]
@ShilpaGhanashyamGore I'm sorry - I know this is bad, but you can reuse your code. All that Swagger does is to provide a framework for APIs. You can use the code from this PR to add it to the generated stubs. @lgfrbcsgo is currently writing the config files for your specs. He will let you know as soon that is done. right? right? right! :balloon:

**Comment by ShilpaGhanashyamGore** [comment]
Closing this pull request as we are going to create a new one using swagger.

**Pull request closed without merging**
