### PR TITLE
define basic sequelize models for relationships

### PR DESCRIPTION
**Pull request by Gillian0023**

### CODE REVIEW

**Review by FelsyWaschbaer — CHANGES_REQUESTED** [review]
Relationship doesn't have a Relationship type yet.

**Comment by Gillian0023** [comment]
@FelsyWaschbaer where is the new structure?

**Comment by FelsyWaschbaer** [comment]
We've  been discussing it in #28 . Ansijn made the last comment about the overall structure

**Comment by Gillian0023** [comment]
@FelsyWaschbaer Yeah, this is exactly following that structure. you mean the relationships model is not right? relationship_type_id is the foreign key for relationships which I have defined in bulidRelations.js

**Comment by FelsyWaschbaer** [comment]
Ah, I see. Good that we've talked about it ;-)

**Review by FelsyWaschbaer — APPROVED** [review]

**Comment by Henni** [comment]
fixed #28

**Pull request merged**
