### PR TITLE
context for app.js + restructuring

### PR DESCRIPTION
**Pull request by TimHenkelmann**
created context for app.js to handle sequelize functions in controllers etc.

### CODE REVIEW

**Review by ShilpaGhanashyamGore — APPROVED** [review]
Tried and tested ! Looks good!

**Comment by kordianbruck** [comment]
Great! :tada:

**Comment by sacdallago** [comment]
WOW, that code looks amazing and I've never seen it before 🤣

**Comment by TimHenkelmann** [comment]
Special thanks go out to our muse @sacdallago !

**Pull request merged**
