### PR TITLE
Mocha support + fixed errors based on the mocha test

### PR DESCRIPTION
**Pull request by Sandr0x00**

### CODE REVIEW

**Comment by Sandr0x00** [comment]
@Henni i get an error from travis. Lint is complaining that `describe` is not defined.
Problem here is, that this stuff is mocha stuff and it is as it should [be](https://mochajs.org/#getting-started). Can we ignore the `mocha` folder somehow?

**Comment by Henni** [comment]
@Sandr00 fixed

@kordianbruck are you ok with a bit messy git history or do you want us to clean up (rebase) before merging PRs?

**Review by kordianbruck — APPROVED** [review]
Looks good

**Comment by kordianbruck** [comment]
@Henni We can squash and merge directly in github - no need to rebase ;)

**Pull request merged**
