### PR TITLE
Unstructured definitions

### LINKED ISSUE #26: Sequelize Models for Unstructured Data
Create the sequelize models for unstructured data. As of now, the following tables should be created:

- Pages (id, url, download_link)
- Terms (id, term)
- Contains (id, term_id, page_id, occurences)

### PR DESCRIPTION
**Pull request by lukasstreit**
Turns our models where partly implemented which is why I only needed to create the dsap modules and make some changes to the model/ models.
Couldn't get the sequelize automatic table creation to work which is why I wasn't able to test yet. These are pretty simple changes so everything should be fine.
Changed use of page in model to website in order to increase consistency because website is used in the api spec. Closes #26

### CODE REVIEW

**Review by kordianbruck — APPROVED** [review]
Fine for now

**Comment by kordianbruck** [comment]
@LukasS96 whats the problem with automatic table creation?

**Comment by lukasstreit** [comment]
If I understand correctly the sequelize.sync call should create the necessary tables automatically in my localhost postgresql. For me it doesn't do that and when trying to make an api call I get the error message: relation <tablename> does not exist, where tablename is the name of the required table depending on the request 

Edit: I'm talking about the sequelize.sync call in app.js to be precise

**Comment by sacdallago** [comment]
It might be because in fact things are not being synced. I'm not entirely understanding the flow of the application right now, but to me it seems that the application is not at all loading the controllers, thus none of the tables get ever written. Basically my last point in #31

**Pull request merged**
