### PR TITLE
Move relations into models

### PR DESCRIPTION
**Pull request by Henni**
refactored the app to look similar to https://github.com/sequelize/express-example
This moves all relations from the `buildRelations.js` to the source models.

### CODE REVIEW

**Review by Sandr0x00 — CHANGES_REQUESTED** [review]
Please update the mocha test as well.

**Comment by Henni** [comment]
@Sandr00 I'll rewrite the Mocha tests in a separate PR.

**Review by Sandr0x00 — APPROVED** [review]

**Comment by Henni** [comment]
nevermind... here they are :)

**Review by TimHenkelmann — APPROVED** [review]
Great job @Henni ! 
I just resolved the conflicts, so maybe have a look into it before you merge

**Comment by Henni** [comment]
awesome work @TimHenkelmann

**Pull request merged**
